# Generated by Django 3.2.18 on 2023-09-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_main',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='ORDERMAIN',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.order_main'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='STAFF',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.staff'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='CUSTOMER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.customer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='MENU',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.menu'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='LOGIN',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.login'),
        ),
        migrations.AlterField(
            model_name='order_delay',
            name='ORDERMAIN',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.order_main'),
        ),
        migrations.AlterField(
            model_name='order_main',
            name='CUSTOMER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.customer'),
        ),
        migrations.AlterField(
            model_name='order_sub',
            name='MENU',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.menu'),
        ),
        migrations.AlterField(
            model_name='order_sub',
            name='ORDERMAIN',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.order_main'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ORDERMAIN',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.order_main'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='CUSTOMER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.customer'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='MENU',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.menu'),
        ),
        migrations.AlterField(
            model_name='special_menu',
            name='MENU',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.menu'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='LOGIN',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menuapp.login'),
        ),
    ]
