# Generated by Django 3.2.18 on 2023-09-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_auto_20230926_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='time',
            field=models.CharField(default='', max_length=30),
        ),
    ]
